[package]
name = "untitled-smaps-poller"
version = "0.1.0"
edition = "2021"
license = "GPL-3.0-only"

[dependencies]
clap = { version = "4.5.32", features = ["derive"] }
env_logger = "0.11.7"
log = "0.4.27"
plotters = "0.3.7"
procfs = "0.17.0"
regex = "1.11.1"
signal-hook = "0.3.17"
